version: '3.8'
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
  backend:
    build: ./backend
    restart: always
    ports:
      - 80:80
    depends_on:
      - mongo
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3.12-management
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
      - 1883:1883
    command: >
      bash -c "
        rabbitmq-plugins enable rabbitmq_mqtt &&
        rabbitmq-server
      "
  data-generator:
    build: ./data-generator
    restart: always
    depends_on:
      - rabbitmq
volumes:
  mongodb_data: