version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 8080:8080
    depends_on:
      - backend
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
  backend:
    build: 
      context: ./backend
    restart: always
    ports:
      - 8081:80
    depends_on:
      - mongo
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3.12-management
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
      - 1883:1883
    command: >
      bash -c "
        rabbitmq-plugins enable rabbitmq_mqtt &&
        rabbitmq-server
      "
  data-generator:
    build: ./data-generator
    restart: always
    volumes:
      - ./data-generator/config.json:/app/config.json
    depends_on:
      - rabbitmq
volumes:
  mongodb_data: